### ISSUE TITLE
Automatically build pkgdown documentation 

### ISSUE THREAD

**Issue by krlmlr** [poissonconsulting/chk#10]
Is there a reason not to?

Two options to do this that work out of the box:

- `usethis::use_pkgdown_travis()`
- `tic::use_tic()`

I'd recommend to host pages from the `gh-pages` branch.

**Comment by joethorley** [comment]
Great - no there is no reason not to. I'd just never tried.

Note why do you recommend gh-pages? Is it to stop the master branch having large commits on it?

**Comment by krlmlr** [comment]
1. With automated commits to `master` you need to pull/fetch more often.

2. A `docs` directory has the advantage that changes to the rendered documentation are tracked and can be reviewed later, especially if you develop in branches and the automation is allowed to update that branch. But this can get ugly with long-lived or overlapping pull requests, so it's better anyway to build docs only on master. That given, there's no real advantage of having the docs in a subdirectory, and the isolated (orphaned) branch becomes the clearly better alternative.

**Comment by krlmlr** [comment]
Implementation looks good. Are the deploy keys set up correctly? Are the package docs served from the `gh-pages` branch?

**Comment by joethorley** [comment]
I've made you an admin on the chk repository so you can see. The deploy key appears to be correct (its just never been used) and a `gh-pages` branch exists but it doesn't have any .html files. Travis errors out when trying to build. I'll add some screenshots of the various components below.

**Comment by joethorley** [comment]
![Screen Shot 2019-09-11 at 09 09 55](https://user-images.githubusercontent.com/613671/64714734-f946b900-d473-11e9-83bf-08969f30e5d8.png)

![Screen Shot 2019-09-11 at 09 11 31](https://user-images.githubusercontent.com/613671/64714845-327f2900-d474-11e9-8915-40b91702d3a8.png)

**Comment by joethorley** [comment]
I'm using travis.com could this be the problem?

**Comment by krlmlr** [comment]
I made it work using a custom version of the travis package. For some reason the builds fail when I add a `GITHUB_PAT` environment variable -- perhaps you need to do it? Can you please create a token without scopes at https://github.com/settings/tokens/new and then create a new secret environment variable `GITHUB_PAT` in https://travis-ci.com/poissonconsulting/chk/settings ?

**Comment by joethorley** [comment]
Done
