### ISSUE TITLE
Prevent call from appearing in error message

### ISSUE THREAD

**Issue by ngreifer** [poissonconsulting/chk#112]
When an error is thrown (i.e., as the result of `err()` or ` chk_` function), the error thrown always says 
```
Error in `err()`:
```
The user should not see `err()` and likely doesn't know what it is, so that part of the error message is confusing and unnecessary. It doesn't actually tell the user where the error is; it appears to be in a function `err()` that they did not call. It would be great if `err()` would not display the function call unless requested, similar to `rlang::abort()` doesn't or `stop(., call. = FALSE)`. This is due to using `rlang::exec()` in the `err()` call rather than calling `rlang::abort()` directly; for some reason using `exec()` triggers `call` to be found and supplied. Thanks!

**Comment by joethorley** [comment]
Thanks @ngreifer - we'll look into

**Comment by joethorley** [comment]
This was a good idea - I've switched to `rlang::abort()` and set the call value so that now the code tells the user where the error is conditional on it being informative

``` r
library(chk)
chk_string(1)
#> Error:
#> ! `1` must be a string (non-missing character scalar).

fun <- function(x) chk_string(x)
fun(1)
#> Error in `fun()`:
#> ! `x` must be a string (non-missing character scalar).
```

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ngreifer** [comment]
This is still a bit of a problem with all the `chk_` functions, which still just display the location of the error, even if that is in a non-user-visible function. Also, in `err()`, the default to `call` is `caller_call(3)` which seems arbitrary (i.e., is `err()` supposed to be used 3 function calls deep?). Not sure what a sensible default is, but I don't know if 3 is it.
