### ISSUE TITLE
Suggestion: add `inclusive` argument to `chk_range()`

### ISSUE THREAD

**Issue by ngreifer** [poissonconsulting/chk#120]
`chk_range()` and `vld_range()` use `<=` and `>=` to check that the values are in the range (inclusive), but users might also want an "exclusive" range check, i.e., using `<` and `>`. An example use case would be checking that a value is a proportion between 0 and 1 but neither 0 nor 1. I'm imagining this could be done with a new function or just an argument to `chk_range()` to toggle whether inclusive or exclusive checks are to be done. Thanks.

**Comment by joethorley** [comment]
thanks @ngreifer - that makes a lot of sense. I've added it to the to do list. Not sure which option we will go with at this point.
