### ISSUE TITLE
complete separation of vld_ functions.

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/chk#18]
As done in `chk_number.R`

**Comment by joethorley** [comment]
I'm thinking `vld-number.R` etc with seealso to go back and forth with chk_ variants.

**Comment by joethorley** [comment]
@inheritSection might be helpful

**Comment by joethorley** [comment]
Actually I think the best way is as I have done for
`chk-flag.R`, `chk-lgl.R` and `chk-dir.R`.

**Comment by joethorley** [comment]
Preparatory tasks:

- [ ] Install R 3.6.1
- [ ] Install latest version of Rstudio
- [ ] Clone poissonconsulting/chk with SSH to hard drive using Rstudio
- [ ] Build chk package
- [ ] Run tests on chk package
- [ ] Check chk package
- [ ] Create branch devayla and push to repository

**Comment by krlmlr** [comment]
Agreed to use one help page per `chk_` + `vld_` pair instead, grouping related checkers in pkgdown. It would be useful to have all checkers in a separate single document, such as a "get started" vignette.

**Comment by joethorley** [comment]
Added get started vignette with all checkers
https://poissonconsulting.github.io/chk/articles/chk.html

**Comment by joethorley** [comment]
Also we can use @family rd to group checkers from separate files

**Comment by aylapear** [comment]
I have a couple clarification questions about the preparatory tasks. 

My understanding of Travis CI is that when you send a pull request to GitHub it runs the tests and builds if all stages pass. Are bullet points 3 to 7 instructing me to clone the repo, create a new branch, send a pull request which triggers the tests to be run and a build if they are successful, and then for me to check whether the build passed or not? 

For the last bullet point is the OrcID you are referring to from this website https://orcid.org/ ?

Also is this the correct forum to be asking a clarification question like this?

**Comment by joethorley** [comment]
Good questions

> 
> My understanding of Travis CI is that when you send a pull request to GitHub it runs the tests and builds if all stages pass. 

Correct

Are bullet points 3 to 7 instructing me to clone the repo, create a new branch, send a pull request which triggers the tests to be run and a build if they are successful, and then for me to check whether the build passed or not?

Yes

> 
> For the last bullet point is the OrcID you are referring to from this website https://orcid.org/ ?

Yes

> 
> Also is this the correct forum to be asking a clarification question like this?

Generally no - in this case yes but we'll get you set up on slack

**Comment by joethorley** [comment]
done
