### ISSUE TITLE
Define behavior for vld_true(structure(TRUE, x = "y"))

### ISSUE THREAD

**Issue by krlmlr** [poissonconsulting/chk#27]
Currently this would be `FALSE`, do we want this to be `TRUE` ?

https://github.com/r-lib/backports/issues/22

**Comment by joethorley** [comment]
Yes - so matches behaviour of `isTRUE()`

**Comment by krlmlr** [comment]
With R 3.6:

``` r
isTRUE(structure(TRUE, x = "y"))
#> [1] TRUE
```

<sup>Created on 2019-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`FALSE` with R 3.3.

**Comment by krlmlr** [comment]
Oh, I misunderstood. So we're changing the implementation?

**Comment by joethorley** [comment]
Not sure - let's discuss later today

**Comment by joethorley** [comment]
I've gone with 
```
is.logical(x) && length(x) == 1L && !anyNA(x) && x
```
