### ISSUE TITLE
\Sexpr{} expresson NOTE when submitting to Rhub

### ISSUE THREAD

**Issue by joethorley** [poissonconsulting/chk#33]
```
❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: 'Joe Thorley <joe@poissonconsulting.ca>'
  
  New submission
  
  Package has help file(s) containing install/render-stage \Sexpr{} expressions but no prebuilt PDF manual.
```

**Comment by joethorley** [comment]
@krlmlr - Any thoughts on what's causing this note when checking chk with Rhub?

**Comment by krlmlr** [comment]
Can you try building the package with `R CMD build` or pkgbuild -- including the manual -- and then sending to Rhub? I haven't found how to do this with the {rhub} package.
