### ISSUE TITLE
update deprecated.R file 

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/chk#35]
- change all calls to `.Deprecated` to `deprecated_soft()`
- remove arguments (ex. (x)) in `what =` & `with =` parameters of deprecated_soft 
    - Example of corrected code:  `deprecate_warn("0.2.0", what = "chk_files()", details = "Please use `chk_all(x, chk_file)`")`
- add tests to ensure the deprecated code is working correctly

**Comment by joethorley** [comment]
Done by Kirril
