### ISSUE TITLE
Update verbosity settings for deprecated functions

### ISSUE THREAD

**Issue by aylapear** [poissonconsulting/chk#38]
- add test to confirm deprecated message is occurring
- then add code to suppress deprecated warnings 

reference: lifecycle verbosity doc examples

**Comment by krlmlr** [comment]
Can be done with

```r
rlang::scoped_options(lifecycle_verbosity = "error")
```

or 

```r
rlang::scoped_options(lifecycle_verbosity = "quiet")
```

See e.g. https://github.com/tidyverse/tibble/blob/master/R/compat-lifecycle.R#L3-L7.
