### ISSUE TITLE
chk_* functions to return input ?

### ISSUE THREAD

**Issue by moodymudskipper** [poissonconsulting/chk#77]
Hi all,

`chk_*` functions all return `NULL` as far as I can see. It is at odds with other assertion packages *{assertive}* and *{checkmate}* which return the unchanged inputs invisibly.

It would allow things like `return(chk_character(value))` or `if(chk_scalar(cond)) expr`.

Maybe it's about performance ? If not I think changing the behavior would avoid surprises from users used to the other behavior.

Thanks!

**Comment by joethorley** [comment]
Hi @moodymudskipper 

Good question - I did this in [checkr](https://github.com/poissonconsulting/checkr) the precursor to chk but came to the conclusion that speed is of the essence and so now just return NULL.

Note you can replace `if(chk_scalar(cond)) expr` with `if(vld_scalar(cond)) expr`

**Comment by moodymudskipper** [comment]
That's fair!
