### ISSUE TITLE
Single function for testing scalar

### ISSUE THREAD

**Issue by pkrog** [poissonconsulting/chk#88]
## Your Idea
I often test in my code that an argument is a scalar, of some atomic type, that cannot be NA.
For this I have understand that three functions are needed in `chk` package :
```r
chk::chk_character(path) 
chk::chk_scalar(path) 
chk::chk_not_any_na(path)
```
Would it be possible to have a one liner for this recurring pattern (like `chk_scalar_*`)?
I may try to write this code myself and send a pull request if you agree.

**Comment by pkrog** [comment]
Sorry to have bothered you. I have found `chk_string`, `chk_flag`, `chk_lgl` and `chk_number` inside the `chk-families` vignette.
Maye this aspect should be shortly described inside the main vignette.
Thanks for your great package by the way.

**Comment by joethorley** [comment]
Thanks @pkrog - we are planning on improving our documentation.

**Comment by joethorley** [comment]
Note we are planning on soft-deprecating the scalar functions that *allow* missing values (they cause confusion) with the exception of `chk_lgl`. they are

```
chk_wnum() vld_wnum() | Check Whole Numeric Scalar
chk_dbl() vld_dbl() | Check Double Scalar
chk_chr() vld_chr() | Check Character Scalar
```
